name: route
description: A route on a map
version: 1.0.0+1
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  bounding_box:
    path: ../bounding_box
  distance:
    git:
      url: https://github.com/kirpal/dart_distance
      ref: nullsafety
  gpx:
    git: https://github.com/kirpal/dart-gpx
  equatable: ^2.0.2
  google_polyline_algorithm: ^3.1.0
  json_annotation: ^4.0.1
  latlong2: ^0.8.0

dev_dependencies:
  build_runner: ^2.0.3
  json_serializable: ^4.1.2
  test: ^1.15.6
  very_good_analysis: ^2.0.0
