name: snap_path
description: An app to measure and create running routes
publish_to: 'none'

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^4.1.2
  path_drawing: ^0.4.1
  flutter_map: ^0.10.1
  latlong: ^0.6.1
  location: ^3.0.2
  http: ^0.12.1
  charts_flutter: ^0.9.0
  solid_bottom_sheet: ^0.1.9
  flutter_feather_icons: ^1.0.3
  auto_size_text: ^2.1.0
  shared_preferences: '>=0.5.7+3 <2.0.0'
  distance: ^0.1.1
  equatable: ^1.2.0
  polyline: ^1.0.2
  breakpoint: ^1.0.1+2
  url_launcher: ^5.4.10
  gpx: ^0.0.3
  wc_flutter_share: ^0.2.2
  firebase_dynamic_links: ^0.5.1
  receive_sharing_intent: ^1.4.0+2
  flutter_svg: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.1.1
  flutter_launcher_icons: ^0.7.5
  flutter_native_splash: ^0.1.9

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/illustrations/

flutter_icons:
  android: true
  ios: true
  image_path_android: 'assets/launcher/android_icon.png'
  image_path_ios: 'assets/launcher/ios_icon.png'
  adaptive_icon_background: '#ffffff'
  adaptive_icon_foreground: 'assets/launcher/android_foreground.png'

flutter_native_splash:
  image: assets/launcher/splash.png
  color: "ffffff"