name: route_repository
description: A repository for manipulating and fetching routes
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  mapbox_api_client:
    path: ../mapbox_api_client
  route:
    path: ../route

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^1.0.4