name: elevation_repository
description: A repository for retrieving information relating to elevation
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  mapbox_api_client:
    path: ../mapbox_api_client
  route:
    path: ../route
  distance:
    git:
      url: https://github.com/kirpal/dart_distance
      ref: nullsafety
  freezed_annotation: ^0.14.2

dev_dependencies:
  build_runner: ^2.0.3
  freezed: ^0.14.2
  mocktail: ^0.1.1
  test: ^1.15.6
  very_good_analysis: ^1.0.4
