name: search_repository
description: A repository for searching locations&#x2F;places
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  bounding_box:
    path: ../bounding_box
  mapbox_api_client:
    path: ../mapbox_api_client
  route:
    path: ../route
  meta: ^1.3.0

dev_dependencies:
  mocktail: ^0.1.1
  test: ^1.15.6
  very_good_analysis: ^1.0.4
