name: saved_route_repository
description: A repository for saving and retrieving saved routes
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  route:
    path: ../route
  rxdart: ^0.27.0
  route_storage_client:
    path: ../route_storage_client

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^1.0.4
