name: mapbox_api_client
description: An api client for interfacing with the mapbox backend
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  bounding_box:
    path: ../bounding_box
  route:
    path: ../route
  dio: ^4.0.0
  image: ^3.0.2
  json_annotation: ^4.0.1

dev_dependencies:
  build_runner: ^1.12.2
  json_serializable: ^4.1.0
  test: ^1.16.8
  very_good_analysis: ^2.0.0

dependency_overrides:
  collection: ^1.15.0
  quiver: ">=0.22.0 <4.0.0"
  xml: ^5.0.2
